version: "3.8"

services:
  miyo:
    container_name: miyo
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - 9452:9452
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
