services:
  miyo:
    container_name: miyo
    image: ghcr.io/veirt/miyo:latest
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - 9452:9452
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
